- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - gnupg2

- name: Add the NodeJS apt key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Install nodejs package
  apt:
    name:
      - "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    update_cache: true

- name: Install npm package separately
  apt:
    name:
      - npm
    update_cache: true
  when: nodejs_install_npm_separately
